FROM golang:1.23 AS builder

WORKDIR /app
COPY simple-control-plane.go .
COPY go.mod go.sum ./
RUN go mod download
RUN CGO_ENABLED=0 go build -o control-plane simple-control-plane.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates wget
WORKDIR /app
COPY --from=builder /app/control-plane .
EXPOSE 8081
CMD ["./control-plane"]
