server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  type: sqlite
  path: /app/data/vault.db

control_plane:
  enabled: true
  url: http://host.docker.internal:8081
  heartbeat_interval: 30s
  retry_interval: 5s
  max_retries: 3
  timeout: 10s

security:
  master_key_file: /app/config/master.key
  rotation_interval: 30d
  backup_enabled: false

logging:
  level: info
  file:
    path: /app/data/agent.log
    max_size: 100
    max_age: 30
    max_backups: 10
    compress: true

performance:
  metrics:
    enabled: true
