apiVersion: v1
kind: Namespace
metadata:
  name: vault-agent
  labels:
    name: vault-agent
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent
  namespace: vault-agent
  labels:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: service-account
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-agent
  labels:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-agent
  labels:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-agent
subjects:
- kind: ServiceAccount
  name: vault-agent
  namespace: vault-agent