apiVersion: v1
kind: Service
metadata:
  name: vault-agent
  namespace: vault-agent
  labels:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: server
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: vault-agent-metrics
  namespace: vault-agent
  labels:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8201"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8201
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: vault-agent-headless
  namespace: vault-agent
  labels:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8200
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: vault-agent
    app.kubernetes.io/component: server