apiVersion: v2
name: vault-agent
description: A Helm chart for Vault Agent - Decentralized Key Management Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://vault-agent.com
sources:
  - https://github.com/vault-agent/vault-agent
maintainers:
  - name: Vault Agent Team
    email: support@vault-agent.com
    url: https://vault-agent.com
keywords:
  - vault
  - secrets
  - security
  - encryption
  - key-management
annotations:
  category: Security
  licenses: MIT
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "25.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "7.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled